<img src="imagenes/ia.png", width="200"\>
# Introducción a Numpy y Matplotlib

## Inicialización de una libreta IP[y]

Para inicializar la libreta y poderla utilizar con `numpy` y `matplotlib`, y asegurarse que los gráficos se presenten donde deben de estar es necesario ejecutar las siguientes instrucciones:

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

Recuerda que hay que ejecutar cada celda (cell) con *ctrl-enter* o con el simbolo de la flechita arriba de la libreta.

La primer linea es un comando específico de `Jupyter` conocidos como *comandos mágicos*. En este comando le especificamos a la libreta que vamos a utilizar matplotlib para hacer gráficas y que queremos que las anexe dentro del documento. Existen muchos comandos mágicos, algunos muy útiles que vamos a ir viendo sobre la marcha. Para una explicacion completa está la libreta http://nbviewer.ipython.org/github/ipython/ipython/blob/1.x/examples/notebooks/Cell%20Magics.ipynb. 


## Inicializando variables en Numpy

Numpy agrega a python básicamente dos nuevos tipos o clases, de los cuales solo nos vamos a interesar por los arreglos multidimensionales o `ndarray`. La manera más sencilla de crear un array (vector o matriz) es utilizando `array` como:

In [2]:
# Crea un objeto vector
vector_a = np.array([1, 3.1416, 40, 0, 2, 5])
print("vector a = \n{}".format(vector_a)) 

      # Crea una matriz
matriz_A = np.array([[1, 2], [3, 4], [5, 6]])
print("matriz A = \n{}".format(matriz_A)) 


vector a = 
[  1.       3.1416  40.       0.       2.       5.    ]
matriz A = 
[[1 2]
 [3 4]
 [5 6]]


El autocompletado funciona muy bien en las libretas de `Jupyter` usando `TAB`. Si quieres conocer la documentación de una función, solo tienes que colocar el cursos al final de ella y utilizar `Shift-TAB` (hacerlo repetidas veces cambia el detalle de la documentación).

In [3]:
vr = np.array

Esta es la manera más directa pero no la única (y en muchos casos la mas usada) para crear nuevos vectores multidimensionales. Existen otras maneras de generar arreglos como son las funciones:

* `arange(ini=0, fin, inc=1)`: Devuelve un ndarray iniciando en ini y terminando en fin, con incrementos de inc

* `zeros(dim)`: Devuelve un ndarray de dimensión dim (si es un escalar se considera un vector, si es una tupla de números entonces
son las dimensiones del ndarray), con todas sus entradas en cero. 
      
* `ones(dim)`: Similar a zeros() pero con unos.
    
* `eye(x, y=none)`: si solo se tiene el argumento x devuelve una matriz identidad de $x \times x$. Si se encuentra y,
entonces una matriz diagonal rectangular de dimensión x por y.
      
* `zeros_like( x )`: Un ndarray de ceros de la misma dimensión que x (igual existe ones_like).
    
* `linspace(inicial, final, elementos)`: Devuelve un ndarray de una dimensión iniciando en inicial, hasta final de 
manera que existan elementos numeros igualmente espaciados. Muy útil para graficación principalmente.
      
* `random.rand(dim1, dim2, ...)`: Devuelve un ndarray de dimensiones dim1 por dim2 por ... con números aleatorios
generados por una distribución uniforme entre 0 y 1. 
      
Veamos unos cuantos ejemplos:

In [4]:
vZ = np.zeros(5)
print("Un vector de ceros con 5 valores")
print(vZ)

Un vector de ceros con 5 valores
[ 0.  0.  0.  0.  0.]


In [5]:
mO = np.ones((3, 10))
print("Una matriz de 3 x 10 de puros unos")
print(mO)

Una matriz de 3 x 10 de puros unos
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [6]:
va = np.arange(10)
print("va = ")
print(va)

va = 
[0 1 2 3 4 5 6 7 8 9]


In [7]:
vb = np.arange(20,-10,-5)
print("vb = ")
print(vb)

vb = 
[20 15 10  5  0 -5]


In [8]:
print("Una matriz de ceros de las dimensiones de mO:")
print(np.zeros_like(mO))

Una matriz de ceros de las dimensiones de mO:
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [9]:
mA = np.random.rand(5, 12)
print("Y una matriz con números aleatorios bajo una distribución uniforme entre 0 y 1")
print(mA)

Y una matriz con números aleatorios bajo una distribución uniforme entre 0 y 1
[[ 0.54766478  0.59788095  0.66331026  0.55829477  0.1967111   0.54979437
   0.67351811  0.38376541  0.98973658  0.03336959  0.0908654   0.05314813]
 [ 0.71113     0.82049712  0.75387947  0.87199469  0.78487201  0.76816155
   0.33641073  0.78934424  0.0562927   0.02613598  0.62495696  0.79836836]
 [ 0.25805689  0.33901751  0.19493585  0.42288527  0.65388525  0.69525123
   0.85738587  0.70368442  0.67051569  0.58337486  0.95277132  0.74685197]
 [ 0.16786779  0.72829236  0.77914081  0.05327231  0.60186926  0.75998465
   0.98658208  0.07016912  0.73378139  0.55095411  0.64832218  0.22144978]
 [ 0.43519895  0.30785437  0.76993944  0.7526204   0.03151399  0.30343296
   0.04992953  0.54636572  0.53825316  0.36240258  0.37158746  0.93155274]]


### Ejercicio: 

En la siguiente celda (o puedes crear las que consideres convenientes) crea las siguientes matrices:

* Una matriz de 4 por 6 con valores aleatorios de acuerdo a una distribución normal con media cero y varianza unitaria.
    
* Un vector de 10 elementos con valores aleatorios de números enteros entre 4 y 100
    
* Una matriz diagonal de 5 por 5 cuyos elementos de la diagonal sean (1, 2, 3, 4, 5)

In [10]:
# Introduce aqui tus respuestas
#Distribución normal
mu, sigma = 0, 1 # media y desvio estandar
mN = np.random.normal(mu, sigma, (4,6)) #creando muestra de datos
print("Una matriz con números aleatorios de acuerdo a una distribución normal con media cero y varianza unitaria")
print(mN,"\n\n")
#nuúeros aleatorios entre 4 y 100
numeros = np.random.randint(4, 100, 10) #creando muestra de datos
print("Un vector de 10 elementos con valores aleatorios de números enteros entre 4 y 100")
print(numeros,"\n\n")
#matriz diagonal
aD=np.zeros((5,5))
np.fill_diagonal(aD,[i for i in range(1,6)]) #creando muestra de datos
print("Una matriz diagonal de 5 por 5 cuyos elementos de la diagonal sean (1, 2, 3, 4, 5)")
print(aD)

Una matriz con números aleatorios de acuerdo a una distribución normal con media cero y varianza unitaria
[[-0.57919285 -0.74987803  0.15405211  0.22651765 -1.78323953  1.00465048]
 [ 0.07655402 -1.5609701   0.02184541 -0.25913524 -0.64350403  0.73639957]
 [-0.25556848 -0.06938845  1.22015615 -1.07854417  1.42141187 -1.23415367]
 [ 0.12675676  0.91669394 -1.64236323 -0.35692525 -0.63862144  0.0584492 ]] 


Un vector de 10 elementos con valores aleatorios de números enteros entre 4 y 100
[85 39 59 93 63 26 75 66 15 74] 


Una matriz diagonal de 5 por 5 cuyos elementos de la diagonal sean (1, 2, 3, 4, 5)
[[ 1.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.]
 [ 0.  0.  3.  0.  0.]
 [ 0.  0.  0.  4.  0.]
 [ 0.  0.  0.  0.  5.]]


## Operaciones básicas de los ndarray

La mayoría de las operaciones que se pueden aplicar e los ndarray se encuenran en el espacio de nombres de np, y las cuales son bastante directas tal como:

    b = np.sin(a)

la cual devuelve en b un ndarray de las mismas dimensiones que a, cuyas entradas son el seno de las entradas de a (en radianes).
Así, parece inecesario explicar las funciones cos, tan, tanh, acos, asin, etc..

Otras funciones muy útiles no son tan directas. Veamos algunas:

    c = a + b

es la suma de dos ndarray, bastante obvio, lo que no lo es tanto es:

    c = a * b

la cual es un ndarray resultante de la *multiplicación punto a punto* de los elementos de a y b, asumiendo que ambos tienen
las mismas diensiones. ¿Y para aplicar un producto matricial? Pues se utiliza el comando dot (o producto punto) el cual puede ser
expresado de dos formas:

    c = np.dot(a, b)
    c = a.dot(b)

La suma de los elementos de un ndarray tambien es un método del objeto (como min, max, argmin, argmax, etc...)

    b = a.sum()

es la suma de *todos los elementos del array* mientras que

    b = a.sum(axis=0) 

es un ndarray con una dimensión menos que a, con la suma de las columnas. Veamos unos ejemplos:

In [11]:
# Vamos a generar varios ndarrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.random.rand(2, 3)

print("a = \n{}".format(a))
print("b = \n{}".format(b))

print("Suma de todos los números de b")
print(b.sum())

print("Media de cada columna de a")
print(a.mean(axis=0))

print("Transpuesta de a, forma larga")
print(a.transpose())

print("Transpuesta de a, forma preferida")
print(a.T)

print("10 * b = ")
print(10 * b)

print("a * b =")
print(a * b)

print("2 elevado a la matriz a")
print(np.power(2, a))

print("a elevada al cuadrado (elemento a elemento)")
print(np.power(a, 2))

print("a.dot(b.T) = ")
print(a.dot(b.T))

print("a.dot(b) debería dar error")
print(a.dot(b))

a = 
[[1 2 3]
 [4 5 6]]
b = 
[[ 0.62745462  0.08218137  0.82992956]
 [ 0.11952351  0.00825812  0.54274595]]
Suma de todos los números de b
2.21009311716
Media de cada columna de a
[ 2.5  3.5  4.5]
Transpuesta de a, forma larga
[[1 4]
 [2 5]
 [3 6]]
Transpuesta de a, forma preferida
[[1 4]
 [2 5]
 [3 6]]
10 * b = 
[[ 6.27454616  0.8218137   8.29929556]
 [ 1.19523508  0.0825812   5.42745947]]
a * b =
[[ 0.62745462  0.16436274  2.48978867]
 [ 0.47809403  0.0412906   3.25647568]]
2 elevado a la matriz a
[[ 2  4  8]
 [16 32 64]]
a elevada al cuadrado (elemento a elemento)
[[ 1  4  9]
 [16 25 36]]
a.dot(b.T) = 
[[ 3.28160603  1.76427759]
 [ 7.90030265  3.77586031]]
a.dot(b) debería dar error


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

Como vemos tenemos aqui una bateria completa de funciones, las cuales se aplican en un ndarray. ¿Pero que información tengo de un ndarray? ¿Como puedo componer un ndarray a partir de otros? 

La mejor manera de aprenderlo es experimentando, así que complet el siguiente **Eejercicio**.

### Ejercicio: tTrata de inferir que es lo que debe contener cada array b, c, d, e, f, g, h sin hacer ninguna prueba y escribelos como comentario. Posteriormente, agrega los `print` que consideres necesarios para verificar que valores tiene b, c, d, e, f, g, h .

In [12]:
#Generamos el ndarray
a = np.arange(100)

# Chacamos algunas propiedades
print("El número de dimensiones de a es: {}".format(a.ndim))
print("Y su forma es {}".format(a.shape))
print("Y tiene {} elementos".format(a.size))

#Generamos algunos ndarrays a partir de a
b, c = a[:20], a[20:]
d, e = a[-1:-10:-1], a[10:11]
f = a[::-1]
g = a[a % 5 == 0]
h = f[[1, 15, 60]]

# Ahora trata de inferir que es lo que debe contener cada array b, c, d, e, f, g, h sin hacer ninguna prueba.
#
#   b tendria los primeros 20 del arreglo a
#
#   c tendria del elemento 20 en adelante del arreglo a
#
#   d tendria desde el ultimo elemento, luego restandole 1 al indice hasta llegar a 9 elementos
#
#   e tendria desde el elemento 10 hasta antes del 11, osea 1 elemento
#
#   f como en los primeros dos espacios no tiene nada deben de ser todos los elementos del arreglo a, pero 
#   en reversa, por el -1
#
#   g contiene los elementos del arreglo cuya división entre 5 da 0
#
#   h tiene los elementos 1, 15 y 60, del arreglo f donde estan en forma inversa
#
# Agrega ahora los print que consideres necesarios para verificar que valores tiene b, c, d, e, f, g, h 
print("\nArreglo b\n")
print(b,"\n\n")
print("Arreglo c\n")
print(c,"\n\n")
print("Arreglo d\n")
print(d,"\n\n")
print("Arreglo e\n")
print(e,"\n\n")
print("Arreglo f\n")
print(f,"\n\n")
print("Arreglo g\n")
print(g,"\n\n")
print("Arreglo h\n")
print(h,"\n\n")

El número de dimensiones de a es: 1
Y su forma es (100,)
Y tiene 100 elementos

Arreglo b

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 


Arreglo c

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44
 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69
 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94
 95 96 97 98 99] 


Arreglo d

[99 98 97 96 95 94 93 92 91] 


Arreglo e

[10] 


Arreglo f

[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76 75
 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52 51 50
 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0] 


Arreglo g

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95] 


Arreglo h

[98 84 39] 




A partir de una matriz (un ndarray de dos dimensiones) se pueden ejemplificar otras cosas, por ejemplo:

In [ ]:
#Generamos un arreglo con 100 valores equiespaciados del seno desde 0 a 2$\pi$
a = np.sin(np.linspace(0, 2 * np.pi, 100))

#Lo convertimos en una matriz de 10 por (lo que sea), que lo que sea es 10 en este caso, seguro
b = a.reshape((10, -1))
print("b queda como: \n{}".format(b))
print("donde b tiene {} dimensiones, con una forma {} y con {} elementos.".format(b.ndim, b.shape, b.size))

In [ ]:
#Si queremos convertir un ndarray a un array de una sola dimension (desenrrollar la matriz sería el término ingenieril)
c = b.ravel()

print("La diferencia de a y c sería")
print((a - c).sum())

In [ ]:
# Si queremos hacer que un vector se comporte como un vector renglon
a = np.arange(30).reshape(1,-1)
print("a es de forma {}".format(a.shape))

# Y si queremos que sea un vector columna hacemos esto
b = np.linspace(30, 35, 30).reshape(-1,1)
print("b es de forma {}".format(b.shape))

# Y para hacer una concatenacion de columnas entonces utilizamps la forma especial np.c[]
c = np.c_[a.T, b]
print("c es de forma {}".format(c.shape))

#Y una concatenación de renglones es por lo tanto
d = np.r_[a, b.T]
print("d es de forma {}".format(d.shape))

Las funciones en `numpy` aplican para todos los elementos de un vector. Por ejemplo `np.sin(A)`, `np.log(A)` calculan el seno y el logritmo natural de cad uno de los elementos de `A`. La multiplicación *, suma +, division / y resta - (entre otras operaciones bnarias) se aplican tambien elemento a elemento, y se hacerlo con una constante, esta se generaliza a la dimensión de la matriz. Si bien la función $1/A$ donde $A$ es un vector o una matriz no tiene sentido en matemáticas, en numpy significa dividir 1 entre cada uno de los elementos de $A$ y devolver una matriz de mismas dimensiones que $A$

### Ejercicio

Realiza lo siguiente:

* Genera una matriz de 100 por 5 de forma que en cada columna tengamos lo siguiente:
    
    - En la primer columna los valores entre -1 y 1, equiespaciados
    - En la segunda columna el valor de seno para los valores de la primer columna
    - En la tercer columna el valor de la función logística de los valores de la primer columna, la cual es $g(x) = \frac{1}{1 + \exp(-x)}$
    - En la cuarta columna 1 si el valor de $\sin(x) > 0$ y -1 en otro caso, donde $x$ son los valores de la primer columna (revisa la función np.where)
    - En la quinta columna valores aleatorios de acuerdo a una distribución gaussiana con media 1 y varianza 0.5
        
* Encuentra un arreglo con todos los valores de la función logística, cuando el valor absoluto del seno de x es menor a 0.5
    
* Convierte este arraglo en una matriz con 5 columnas y los renglones que sean necesarios.
        

In [ ]:
#  Escribe aqui tu código
#funcion g
def g(x):
    a=np.copy(x)
    for i in range(len(a)):
        #i=1/(1+np.exp(-i))
        a[i]=1/(1+np.exp(-a[i]))
    return a
#creo el arreglo con ceros al inicio
matriz=np.zeros((100,5))
#obtener las longitudes
alto,largo=matriz.shape
#la primer colunma con valores equidistantes entre -1 y 1
matrizColumna1=np.linspace(-1, 1, alto)
#segunda columna cone l seno de los valores de la columna 1
matrizColumna2=np.sin(matrizColumna1)
#la tercer columna con los valores de la funcion g aplicada a la columna 1
matrizColumna3=np.apply_along_axis(g,0,matrizColumna1)
#columna 4
#los indices donde se cumple la condicion
indices=np.where(np.sin(matrizColumna1)>0)[0]
matrizColumna4=[1 if i in indices else -1 for i in range(alto)]
#columna 5
mu, sigma = 1, np.sqrt(.5) # media y desvio estandar
matrizColumna5 = np.random.normal(mu, sigma, alto) #creando muestra de datos
#concatenar 
matriz=np.c_[matrizColumna1,matrizColumna2,matrizColumna3,matrizColumna4,matrizColumna5]
print("Matriz de 100x5\n")
print(matriz,"\n\n")


indices = np.where(np.abs(matrizColumna2) < 0.5)[0]
print("Indices de todos los valores de la función logística, cuando el valor absoluto del seno de x es menor a 0.5\n")
print(indices,"\n\n")
matriz2=[matrizColumna3[i] if i in indices else 0 for i in range(alto)]
matriz2 = np.array(matriz2).reshape((-1, 5))
print("Valores con valor absoluto del seno de x es menor a 0.5 en matriz de 5 columnas\n")
print(matriz2)


Además de estas funciones, numpy cuenta con funciones del algebra lineal altamente optimizadas (aunque no paralelizadas), las cuales son (entre otras):

* `np.linalg.inv(a)`: Inversa de a
* `np.linalg.pinv(a)`: Pseudoinversa de Ross-Penrose de a (muy útil para nosotros)
* `np.linalg.det(a)`: determinante de a
* `np.linalg.eig(a)`: eigenvalores y eigenvectores de a
* `np.linalg.svd(a)`: Valores singulares de a

## Haciendo gráficas sencillas con Matplotlib

La mejor manera de mostrar como funcionan las facilidades que ofrece matplotlib, es mostrando directamente su uso más sencillo,
así que veamos un ejemplo muy simple. Es importante recordar que en la primer celda de esta libreta se definió la manera de realizar las gráficas (dentro del documento y no como figuras aparte), así como se cargo matplotlib en el espacio de nombres plt.

In [ ]:
# Vamos a hacerlo pasito a pasito

# Primero obtenemos un vector x
x = np.linspace(-np.pi, np.pi, 1000)

# Luego obtenemos un vector y bastante trivial
y = np.sin(x)

# Y ahora hacemos una gráfica bastante básica de x y y
plt.plot(x, y)
plt.xlabel("el eje de las x's")
plt.ylabel("el eje de las y's")
plt.title("Este es un plot bastante trivial y sin mucho chiste")

# Bueno como la gráfica no esta muy bien a lo mejor se ve mejor si modificamos los limites de los ejes
plt.axis([-3.1416, 3.1416, -1.1, 1.1])

Aunque a veces queremos hacer unas gráficas más bien indicativas por lo que un estilo más informal podría ser útil:


In [ ]:
with plt.xkcd():
    plt.plot(x, y)
    plt.xlabel("el eje de las x's")
    plt.ylabel("el eje de las y's")
    plt.title("Este es un plot bastante trivial y sin mucho chiste")
    plt.axis([-3.1416, 3.1416, -1.1, 1.1])

Hay que tener mucho cuidado, ya que si no se utiliza plt.xkcd() dentro de un with, entonces va a modificar todas las graficas que se realicen en la libreta (a veces es deseable, pero es una mejor práctica de programación hacerlo así).

Ahora hagamos una gráfica con varios valores diferentes

In [ ]:
plt.plot(x, np.sin(x), label='seno')

plt.plot(x, 1/(1 + np.exp(-x)), label=u"logística")

plt.plot(x, (0.2 * x * x) - 0.5, label=r'$0.2 x^2 - 0.5$')

plt.axis([-3.1416, 3.1416, -1.1, 1.4])

plt.title("Tres funciones piteras juntas")
plt.xlabel(r"$\theta$ (rad)")
plt.ylabel("magnitud")

plt.legend(loc=0)

Hay muchos tipos de funciones, lo mejor para saber como ustilizar matplotlib es ver la galeria de ejemplo que se encuentran en la ayuda,
y pueden consultarse en http://matplotlib.org/gallery.html (al darle click a una imagen se puede ver el código que la genera).

Por ejemplo si queremos una gráfica tipo pay con estlos diferentes:

In [ ]:
labels = 'Tortas', 'Taquitos', 'Burros', 'Ensaladas'
porcentajes = [15, 30, 45, 10]
colores = ['yellowgreen', 'gold', 'lightskyblue', 'lightcoral']
separa = (0, 0.1, 0, 0) # solo separa la segunda rebanada (i.e. 'Taquitos')

with plt.xkcd():
    plt.pie(porcentajes, explode=separa, labels=labels, colors=colores, autopct='%1.1f%%', shadow=True, startangle=90)
    plt.axis('equal') #Para que el pay se vea como un círculo
    plt.xlabel(u'Lo que como cuando me quedo en la UNISON a mediodía')
    plt.show()



    

O si queremos una gráfica tipo contorno con todo y datos

In [ ]:
# Genera datos en los ejes x y y de forma uniforme entre -2 y 2
# prueba generando 2000 puntos (con y sin colores) pero para 
# 2000 puntos no vayas a dibujar los valores parque no se va a ver nada.
x = np.random.uniform(-2, 2, 200)
y = np.random.uniform(-2, 2, 200)

# Genera los valores en z en cada punto generado, con la función siguiente
z = x * np.exp(-x ** 2 - y ** 2)

# define el grid donde se muestran los datos
xi = np.linspace(-2.1, 2.1, 100)
yi = np.linspace(-2.1, 2.1, 200)

# Genera datos de z interpolados para tener mejor presición en el contorno
from matplotlib.mlab import griddata
zi = griddata(x, y, z, xi, yi, interp='linear')

# Hace una gráfica de contorno con únicamente lineas de nivel.
plt.contour(xi, yi, zi, 15, linewidths=0.5, colors='k')

# Para hacerlo mas acá pues se puede agregar color a cada nivel y agregarle una barra de nivel de color
plt.contourf(xi, yi, zi, 15, cmap=plt.cm.rainbow, vmax=abs(zi).max(), vmin=-abs(zi).max())
plt.colorbar() # draw colorbar

# Grafica los puntos generados sobre el contorno.
plt.scatter(x, y, marker='o', c='b', s=5, zorder=10)

# Hace los límites de la gráfica exactos
plt.axis([-2, 2, -2, 2])

plt.title('Prueba para un contorno con datos generados')

Por último, un detalle muy importante y que puede ser de mucha utilidad: La generación de subplots. Una figura puede contener varias subgraficas, para esto hay que especificar en cuantas gráficas vamos a dividir la figura en forma de renglones y columnas, y luego seleccionar la subgráfica en la que vamos a graficar. Por ejemplo

    plt.subplot(2,2,1)
    
significa que la figura la vamos a dividir en 2 renglones y dos columnas (cuatro subgráficas) y vamos a escribir sobre la subgráfica 1. Lo mejor es ilustrarlo con un ejemplo muy simple.

In [ ]:
x = np.linspace(0, 5, 1000)
y1 = np.exp(-0.2 * x) * np.cos(2 * np.pi * x)
y2 = np.cos(2 * np.pi * x)
y3 = np.exp(0.2 * x) * np.cos(2 * np.pi * x)
y4 = np.exp(-0.1 * x)

plt.subplot(2, 2, 1)
plt.plot(x, y1)
plt.title('Estable subamortiguado')

plt.subplot(2, 2, 2)
plt.plot(x, y2)
plt.title('Criticamente estable')

plt.subplot(2, 2, 3)
plt.plot(x, y3)
plt.title('inestable')

plt.subplot(2, 2, 4)
plt.plot(x, y4)
plt.title('Estable sobreamortiguado')



### Ultimo Ejercicio

Realiza lo siguiente en varias celdas abajo de esta:

* Genera un vector de 1000 datos aleatorios distribuidos de acuerdo a una gaussiana con media 3 y varianza .5, y otro vector con 1000 datos aleatorios distribuidos con una madia 0 y una varianza unitaria. Al concatenar los dos vectores, estás generando una serie de datos proveniente de una distribución conocida como suma de gaussianas. Para ver como es esta distribución de datos, grafíca un histograma (con un número suficiente de bins).

* Genera un vector de datos de entrada `x = np.linspace(0, 1, 1000)` y grafica $\sin(2\pi x)$, $\sin(4\pi x)$, $\sin(8\pi x)$. ¿Que conlusión puedes sacar al respecto? Realiza la gráfica con titulo, ejes, etiquetas y todo lo necesario para que sea publicable.

* Grafica la función $e^{-t}\cos(2\pi t)$ para $t \in [0, 5]$. Asegurate que la gráfica sea una linea punteada de color rojo, que la gráfica tenga título, etiqueta en el eje de $t$ (tiempo), etiqueta en el eje de $y$ (voltaje en $\mu$V), y una nota donde se escriba la ecuación simulada.

* Copia el ejemplo de la galería de matplotlib http://matplotlib.org/examples/pylab_examples/shading_example.html y modificalo para que se grafique dentro de la libreta. Una vez funcionando, comenta *cada linea de código* dejando bien claro **en español y con tus palabras** que es lo que hace cada una de las lineas.

In [ ]:
#Agrega aqui el primer problema y resualve cada problema en una celda independiente.
mu, sigma = 3, np.sqrt(5) # media y desvio estandar
arreglo1 = np.random.normal(mu, sigma, 1000) #creando muestra de datos
print("Vector con numeros aleatorios con mu = {} y varianza = {}\n".format(mu,sigma))
print(arreglo1)
mu2, sigma2 = 0, 1 # media y desvio estandar
arreglo2 = np.random.normal(mu2, sigma2, 1000) #creando muestra de datos
print("Vector con numeros aleatorios con mu = {} y varianza = {}\n".format(mu2,sigma2))
print(arreglo2)

arreglo3 = np.r_[arreglo1, arreglo2]

plt.hist(arreglo3, bins=100)
plt.xlabel("Frecuencia")
plt.title("Suma de gaussianas")


In [ ]:
#segundo Problema
x = np.linspace(0, 1, 1000)
#las 3 funcones
plt.plot(x, np.sin(2*np.pi*x), label="sin(2PI*x)")
plt.plot(x, np.sin(4*np.pi*x), label="sin(4PI*x)")
plt.plot(x, np.sin(8*np.pi*x), label="sin(8PI*x)")

plt.title('Funciones Seno')
plt.xlabel("Radianes")
plt.ylabel("Seno")

plt.legend(loc='best')

In [ ]:
#Tercer Problema
t = np.linspace(0, 5, 100)

plt.plot(t, np.exp(-t) * np.cos(2*np.pi*t), label="(e^-t)cos (2PIt)", color='red', linestyle='--')

plt.title('Voltaje en tiempo')
plt.xlabel("t (tiempo)")
plt.ylabel(r"$\mu V$ (Voltaje)")

plt.legend(loc="best")


In [ ]:
#Cuarto Problema
